/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
<<<<<<< HEAD
import { Route as ApiLoginRouteImport } from './routes/api/login'
import { Route as ApiColaboradoresRouteImport } from './routes/api/colaboradores'
import { Route as ApiApplyMigrationsRouteImport } from './routes/api/apply-migrations'
=======
>>>>>>> abdb50bf565f8f328015be289fdd15bd5a3223ba
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as AuthenticatedGerarFormulariosRouteImport } from './routes/_authenticated/gerar-formularios'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedColaboradoresIndexRouteImport } from './routes/_authenticated/colaboradores/index'
<<<<<<< HEAD
import { Route as ApiColaboradoresIdRouteImport } from './routes/api/colaboradores.$id'
=======
>>>>>>> abdb50bf565f8f328015be289fdd15bd5a3223ba
import { Route as AuthenticatedColaboradoresIdRouteImport } from './routes/_authenticated/colaboradores/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiColaboradoresRoute = ApiColaboradoresRouteImport.update({
  id: '/api/colaboradores',
  path: '/api/colaboradores',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApplyMigrationsRoute = ApiApplyMigrationsRouteImport.update({
  id: '/api/apply-migrations',
  path: '/api/apply-migrations',
  getParentRoute: () => rootRouteImport,
} as any)
=======
>>>>>>> abdb50bf565f8f328015be289fdd15bd5a3223ba
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGerarFormulariosRoute =
  AuthenticatedGerarFormulariosRouteImport.update({
    id: '/gerar-formularios',
    path: '/gerar-formularios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedColaboradoresIndexRoute =
  AuthenticatedColaboradoresIndexRouteImport.update({
    id: '/colaboradores/',
    path: '/colaboradores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
<<<<<<< HEAD
const ApiColaboradoresIdRoute = ApiColaboradoresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiColaboradoresRoute,
} as any)
=======
>>>>>>> abdb50bf565f8f328015be289fdd15bd5a3223ba
const AuthenticatedColaboradoresIdRoute =
  AuthenticatedColaboradoresIdRouteImport.update({
    id: '/colaboradores/$id',
    path: '/colaboradores/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gerar-formularios': typeof AuthenticatedGerarFormulariosRoute
  '/importar': typeof AuthenticatedImportarRoute
<<<<<<< HEAD
  '/api/apply-migrations': typeof ApiApplyMigrationsRoute
  '/api/colaboradores': typeof ApiColaboradoresRouteWithChildren
  '/api/login': typeof ApiLoginRoute
  '/colaboradores/$id': typeof AuthenticatedColaboradoresIdRoute
  '/api/colaboradores/$id': typeof ApiColaboradoresIdRoute
=======
  '/colaboradores/$id': typeof AuthenticatedColaboradoresIdRoute
>>>>>>> abdb50bf565f8f328015be289fdd15bd5a3223ba
  '/colaboradores/': typeof AuthenticatedColaboradoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gerar-formularios': typeof AuthenticatedGerarFormulariosRoute
  '/importar': typeof AuthenticatedImportarRoute
<<<<<<< HEAD
  '/api/apply-migrations': typeof ApiApplyMigrationsRoute
  '/api/colaboradores': typeof ApiColaboradoresRouteWithChildren
  '/api/login': typeof ApiLoginRoute
  '/colaboradores/$id': typeof AuthenticatedColaboradoresIdRoute
  '/api/colaboradores/$id': typeof ApiColaboradoresIdRoute
=======
  '/colaboradores/$id': typeof AuthenticatedColaboradoresIdRoute
>>>>>>> abdb50bf565f8f328015be289fdd15bd5a3223ba
  '/colaboradores': typeof AuthenticatedColaboradoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/gerar-formularios': typeof AuthenticatedGerarFormulariosRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
<<<<<<< HEAD
  '/api/apply-migrations': typeof ApiApplyMigrationsRoute
  '/api/colaboradores': typeof ApiColaboradoresRouteWithChildren
  '/api/login': typeof ApiLoginRoute
  '/_authenticated/colaboradores/$id': typeof AuthenticatedColaboradoresIdRoute
  '/api/colaboradores/$id': typeof ApiColaboradoresIdRoute
=======
  '/_authenticated/colaboradores/$id': typeof AuthenticatedColaboradoresIdRoute
>>>>>>> abdb50bf565f8f328015be289fdd15bd5a3223ba
  '/_authenticated/colaboradores/': typeof AuthenticatedColaboradoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/gerar-formularios'
    | '/importar'
<<<<<<< HEAD
    | '/api/apply-migrations'
    | '/api/colaboradores'
    | '/api/login'
    | '/colaboradores/$id'
    | '/api/colaboradores/$id'
=======
    | '/colaboradores/$id'
>>>>>>> abdb50bf565f8f328015be289fdd15bd5a3223ba
    | '/colaboradores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/gerar-formularios'
    | '/importar'
<<<<<<< HEAD
    | '/api/apply-migrations'
    | '/api/colaboradores'
    | '/api/login'
    | '/colaboradores/$id'
    | '/api/colaboradores/$id'
=======
    | '/colaboradores/$id'
>>>>>>> abdb50bf565f8f328015be289fdd15bd5a3223ba
    | '/colaboradores'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/gerar-formularios'
    | '/_authenticated/importar'
<<<<<<< HEAD
    | '/api/apply-migrations'
    | '/api/colaboradores'
    | '/api/login'
    | '/_authenticated/colaboradores/$id'
    | '/api/colaboradores/$id'
=======
    | '/_authenticated/colaboradores/$id'
>>>>>>> abdb50bf565f8f328015be289fdd15bd5a3223ba
    | '/_authenticated/colaboradores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
<<<<<<< HEAD
  ApiApplyMigrationsRoute: typeof ApiApplyMigrationsRoute
  ApiColaboradoresRoute: typeof ApiColaboradoresRouteWithChildren
  ApiLoginRoute: typeof ApiLoginRoute
=======
>>>>>>> abdb50bf565f8f328015be289fdd15bd5a3223ba
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/colaboradores': {
      id: '/api/colaboradores'
      path: '/api/colaboradores'
      fullPath: '/api/colaboradores'
      preLoaderRoute: typeof ApiColaboradoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apply-migrations': {
      id: '/api/apply-migrations'
      path: '/api/apply-migrations'
      fullPath: '/api/apply-migrations'
      preLoaderRoute: typeof ApiApplyMigrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
=======
>>>>>>> abdb50bf565f8f328015be289fdd15bd5a3223ba
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gerar-formularios': {
      id: '/_authenticated/gerar-formularios'
      path: '/gerar-formularios'
      fullPath: '/gerar-formularios'
      preLoaderRoute: typeof AuthenticatedGerarFormulariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colaboradores/': {
      id: '/_authenticated/colaboradores/'
      path: '/colaboradores'
      fullPath: '/colaboradores/'
      preLoaderRoute: typeof AuthenticatedColaboradoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
<<<<<<< HEAD
    '/api/colaboradores/$id': {
      id: '/api/colaboradores/$id'
      path: '/$id'
      fullPath: '/api/colaboradores/$id'
      preLoaderRoute: typeof ApiColaboradoresIdRouteImport
      parentRoute: typeof ApiColaboradoresRoute
    }
=======
>>>>>>> abdb50bf565f8f328015be289fdd15bd5a3223ba
    '/_authenticated/colaboradores/$id': {
      id: '/_authenticated/colaboradores/$id'
      path: '/colaboradores/$id'
      fullPath: '/colaboradores/$id'
      preLoaderRoute: typeof AuthenticatedColaboradoresIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGerarFormulariosRoute: typeof AuthenticatedGerarFormulariosRoute
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedColaboradoresIdRoute: typeof AuthenticatedColaboradoresIdRoute
  AuthenticatedColaboradoresIndexRoute: typeof AuthenticatedColaboradoresIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGerarFormulariosRoute: AuthenticatedGerarFormulariosRoute,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedColaboradoresIdRoute: AuthenticatedColaboradoresIdRoute,
  AuthenticatedColaboradoresIndexRoute: AuthenticatedColaboradoresIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

<<<<<<< HEAD
interface ApiColaboradoresRouteChildren {
  ApiColaboradoresIdRoute: typeof ApiColaboradoresIdRoute
}

const ApiColaboradoresRouteChildren: ApiColaboradoresRouteChildren = {
  ApiColaboradoresIdRoute: ApiColaboradoresIdRoute,
}

const ApiColaboradoresRouteWithChildren =
  ApiColaboradoresRoute._addFileChildren(ApiColaboradoresRouteChildren)

=======
>>>>>>> abdb50bf565f8f328015be289fdd15bd5a3223ba
const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
<<<<<<< HEAD
  ApiApplyMigrationsRoute: ApiApplyMigrationsRoute,
  ApiColaboradoresRoute: ApiColaboradoresRouteWithChildren,
  ApiLoginRoute: ApiLoginRoute,
=======
>>>>>>> abdb50bf565f8f328015be289fdd15bd5a3223ba
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
